In [78]:
class JSS:
    def __init__(self):
        self.name = input('이름입력:')
        self.age = input('나이') 
    def show(self):
         print('나의 이름은{}, 나이는{}세입니다.'.format(self.name, self.age))

In [79]:
a = JSS()


이름입력:홍길동
나이22


나의 이름은홍길동, 나이는22세입니다.


In [129]:
class JSS2(JSS):
    def __init__(self):
        super().__init__()
        self.gender = input('성별:')
    def show(self):
         print('나의 이름은 {}, 성별은 {}자, 나이는 {}세입니다.'.format(self.name, self.gender, self.age))

In [132]:
a = JSS2()

이름입력:김동혁
나이22
성별:남


In [134]:
a.show()

나의 이름은 김동혁, 성별은 남자, 나이는 22세입니다.


In [180]:
class Book:
    def __init__(self):
        self.author = input('저자입력: ')
        self.name = input('책입력: ')
        self.publisher = input('출판사 입력: ')
        self.date = input('발행일: ')
    def show(self):
        print('이책은 {}(이)고 저자는 {}(이)며 출판일은 {}이고 출판사는 {}입니다.'.format(self.author, self.name, self.publisher, self.date ))

In [184]:
a = Book()

저자입력: 나
책입력: 왜
출판사 입력: 지금까지
발행일: 잠못자?


In [185]:
a.show()

이책은 나(이)고 저자는 왜(이)며 출판일은 지금까지이고 출판사는 잠못자?입니다.


In [3]:
import numpy as np
tpl = (2,3,5)
lst2 = list(tpl)
print(lst2*3)

[2, 3, 5, 2, 3, 5, 2, 3, 5]


In [6]:
arr= np.array(lst2)
print(arr*3)
print(type(arr))

[ 6  9 15]
<class 'numpy.ndarray'>


In [10]:
lst3 = [[1,2,3],[4,5,6],[7,8,9]]
print(lst3)
arr2 = np.array(lst3)
print(arr2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(arr2.dtype)
print(arr2[1][2])

int32
6


In [73]:
arr2[:3,:4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr3 = np.zeros((2,3))
print(arr3)
print(arr3.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [22]:
arr4 = np.ones((2,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
arr5 = np.arange(5)
print(arr5, type(arr5))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [57]:
data = np.arange(12).reshape(4,3)
print(data)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [58]:
data[data>5] = 5
print(data)

[[0 1 2]
 [3 4 5]
 [5 5 5]
 [5 5 5]]


In [50]:
data.mean()

3.75

In [59]:
data[:,[2,0,1]]


array([[2, 0, 1],
       [5, 3, 4],
       [5, 5, 5],
       [5, 5, 5]])

In [61]:
data.mean(0)

array([3.25, 3.75, 4.25])

In [62]:
x = np.array([1,2,3,4,5])
(x>3).sum()

2

In [74]:
(x>3)

array([False, False, False,  True,  True])

In [82]:
import pandas as pd
dic = {'city':['서울', '대전', '대구', '부산', '광주'], 'year' : [2017,2017,2018,2018,2018],'temp':[10,13,20,15,40]}
data = pd.DataFrame(dic)
data

city  year  temp
0   서울  2017    10
1   대전  2017    13
2   대구  2018    20
3   부산  2018    15
4   광주  2018    40

In [117]:
data.index = ['a', 'b', 'c', 'd', 'e']
data

city  year  temp  car   high
a   서울  2017    10   50   True
b   대전  2017    13   40   True
c   대구  2018    20   30   True
d   부산  2018    15   20  False
e   광주  2018    40   10  False

In [98]:
data.loc['a']

city      서울
year    2017
temp      10
Name: a, dtype: object

In [120]:
data.set_index(['도시'])

KeyError: "None of ['도시'] are in the columns"

In [122]:
data.set_index(['도시'], inplace= True)

KeyError: "None of ['도시'] are in the columns"

In [114]:
cars = [50,40,30,20,10]
data['car'] = cars 
data 

city  year  temp  car   high
a   서울  2017    10   50   True
b   대전  2017    13   40   True
c   대구  2018    20   30   True
d   부산  2018    15   20  False
e   광주  2018    40   10  False

In [109]:
data['high'] = data.car >=30
data

city  year  temp  car   high
a   서울  2017    10   50   True
b   대전  2017    13   40   True
c   대구  2018    20   30   True
d   부산  2018    15   20  False
e   광주  2018    40   10  False

In [1]:
data.drop('car', 1)

NameError: name 'data' is not defined

In [4]:

class Shape:
    def __init__(self, x1, y1):
        self.x = x
        self.y = y
    def area(self):
        pass
    def perimeter(self):
        pass
class Ractange(Shape):
    def __init__(self, x, y, width, height):
        super().__init__(x, y)
        self.width = width
        self.height = height
    def area(self):
        return self.width * self.height
    def perimeter(self):
        return 2 * (self.width + self.height)
rect = Ractange(0,0,100,200)
print("사각형의 면적:", rect.area())
print("사각형의 면적:", rect.perimeter())



NameError: name 'x' is not defined